### ISSUE TITLE
Benchmarking of resources does not seem to work accurately on Android.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/SeattleOnAndroid#2]
After wondering why the transition scripts were not working properly on android devices and digging through the log files, we discovered that the initial vessel V1 could not be split due to lack of resources. 

After digging into it a little further, we found that the benchmarking done at install time was not providing accurate measurement of the diskspace. For example, on a tablet that has a sdcard of 24GB, the benchmark reported that a total diskused that was available was 866308096 (20% of that being ~173MB).

Similarly on a phone that had an SD card that had 16GB free space, the benchmarking showed that there was 232812544 available space.

**Comment by aaaaalbert** [comment]
This will be fixed when we update Seattle On Android's code base from Sensibility Testbed app.
